# Generated by Django 3.2.7 on 2021-10-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_roomuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomuser",
            name="last_seen",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
